bbs/urls.py
from django.urls import path
from . import views

app_name    = "bbs"
urlpatterns = [ 
    path('', views.index, name="index"),
    path('<int:pk>/', views.index, name="single"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bbs.urls"), name="bbs"),
]

bbs/models.py
from django.db import models

class Topic(models.Model):

    class Meta:
        db_table = "topic"

    comment     = models.CharField(verbose_name="コメント",max_length=2000)

    def __str__(self):
        return self.comment

bbs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):

    class Meta:
        model   = Topic
        fields  = [ "comment" ]

bbs/views.py
from django.shortcuts import render

from django.views import View

from django.http.response import JsonResponse
from django.template.loader import render_to_string

from .models import Topic
from .forms import TopicForm

class IndexView(View):

    def get(self, request, *args, **kwargs):

        topics  = Topic.objects.all()
        context = { "topics":topics }

        return render(request,"bbs/index.html",context)

    def post(self, request, *args, **kwargs):

        json    = { "error":True }
        form    = TopicForm(request.POST)

        if not form.is_valid():
            print("Validation Error")
            return JsonResponse(json)

        form.save()
        json["error"]   = False

        topics          = Topic.objects.all()
        context         = { "topics":topics }
        content         = render_to_string("bbs/content.html",context,request)

        json["content"] = content

        return JsonResponse(json)

    def delete(self, request, *args, **kwargs):
        
        json    = { "error":True }

        if "pk" not in kwargs:
            return JsonResponse(json)

        topic   = Topic.objects.filter(id=kwargs["pk"]).first()

        if not topic:
            return JsonResponse(json)

        print(request.body)
        print(type(request.body))


        raw_data    = request.body.decode("utf-8")
        data_list   = raw_data.split("&")

        for data in data_list:
            data    = data.split("=")
            print("Key:",data[0], "Value:",data[1])

        #topic.delete()

        json["error"]   = False

        return JsonResponse(json)

index   = IndexView.as_view()

templates/bbs/content.html
{% for topic in topics %}
<div class="border">
{{ topic.comment }}

<form action="{% url 'bbs:single' topic.id %}">
    <input class="btn btn-outline-danger trash" type="button" value="削除">
</form>

</div>
{% endfor %}

templates/bbs/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>簡易掲示板</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>


    <script src="{% static 'js/ajax.js' %}"></script>

</head>
<body>

    <main class="container">
        <form id="form_area" action="" method="POST">
            {% csrf_token %}
            <textarea id="textarea" class="form-control" name="comment"></textarea>
            <input id="submit" type="button" value="送信">
        </form>

        <div id="content_area">{% include "bbs/content.html" %}</div>

    </main>
</body>
</html>